# TODO: 1. Change `appIngressroute` to `appIngressroutes`
# 2. Delete this after the version 2.0.0
{{- if .Values.appIngressroute }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "application-chart-template.fullname" . }}-redirect-to-https
  namespace: {{ $.Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}

{{- if .Values.appIngressroute }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "application-chart-template.fullname" . }}-redirect-to-https
  namespace: {{ $.Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
