remote: origin
target-branch: main
chart-dirs:
  - charts/
# additional-commands:
#   - helm unittest --helm3 -f tests/*.yaml {{ .Path }}
namespace: default
release-label: app.kubernetes.io/namespace
