{{- range $_, $service := .Values.externalIngressroute }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}
spec:
  entryPoints:
    - web
  routes:
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}
          port: {{ $service.port }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}-{{ . }}
        {{- end }}
{{- end }}
---
{{- range $_, $service := .Values.externalIngressroute }}
{{- if has "redirect-to-https" $service.middlewares }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ include "application-chart-template.applicationHosts" $ }} && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}
          port: {{ $service.port }}
      middlewares:
        {{- range without $service.middlewares "redirect-to-https" }}
        - name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}-{{ . }}
        {{- end }}
  tls:
    secretName: {{ include "application-chart-template.fullname" $ }}-tls-secret
{{- end }}
{{- end }}
