{{- range $_, $service := .Values.externalIngressroute }}
{{- if has "redirect-to-https" $service.middlewares }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "application-chart-template.external-service-name" (dict "root" $ "service" $service ) }}-redirect-to-https
  namespace: {{ $.Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
{{- end }}
